package es.usal.bicoverlapper.data;

import java.awt.BorderLayout;

import affymetrix.GDACNetAffx.*;

/**
 *
 * @author  ljevon
 */
public class TestNetAffx extends javax.swing.JFrame {
    
    public GDACNetAffxAnnotationListing m_List;
    
    /** Creates new form TestNetAffx */
    public TestNetAffx() {
        initComponents();
        try
        {
            m_List = new GDACNetAffxAnnotationListing();
            m_List.DataDirectory = "C:\\temp\\";
            m_List.ConnectionIdentifier = "";
            m_List.UserName = "";
            m_List.Password = "";
        }
        catch (Throwable t)
        {
            javax.swing.JOptionPane.showMessageDialog(this, t.getMessage());
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        okButton = new javax.swing.JButton();
        anList = new java.awt.List();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        connectionTextField = new javax.swing.JTextField();
        userTextField = new javax.swing.JTextField();
        pwdTextField = new javax.swing.JTextField();

        getContentPane().setLayout(null);

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        //getContentPane().add(okButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 274, 410, -1));
        getContentPane().add(okButton, new BorderLayout());

        //getContentPane().add(anList, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 410, 200));
        getContentPane().add(anList, new BorderLayout());

        jLabel1.setText("Connection ID");
        //getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 20));
        getContentPane().add(jLabel1, new BorderLayout());

        jLabel2.setText("User");
        //getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 90, 20));
        getContentPane().add(jLabel2, new BorderLayout());

        jLabel3.setText("Password");
        jLabel3.setToolTipText("null");
        //getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 90, 20));
        getContentPane().add(jLabel3, new BorderLayout());

        connectionTextField.setText("connection ID");
        //getContentPane().add(connectionTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 310, -1));
        getContentPane().add(connectionTextField, new BorderLayout());

        userTextField.setText("user name");
        //getContentPane().add(userTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 310, -1));
        getContentPane().add(userTextField, new BorderLayout());

        pwdTextField.setText("password");
        //getContentPane().add(pwdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 310, -1));
        getContentPane().add(pwdTextField, new BorderLayout());

        pack();
    }//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        
        String sel = anList.getSelectedItem();
        int i = anList.getSelectedIndex();
        try
        {
            m_List.RetrieveAnnotationFile(i);
        }
        catch (Throwable t)
        {
            javax.swing.JOptionPane.showMessageDialog(this, t.getMessage());
        } 
         
        
        try
        {
            anList.removeAll();
            
            m_List.ConnectionIdentifier = connectionTextField.getText();
            m_List.UserName = userTextField.getText();
            m_List.Password = pwdTextField.getText();
            m_List.RetrieveAnnotationList();
            long n = m_List.NumAnnotations;
            
            // str = new String();
            //str = "Number annotations = " + n;
            //javax.swing.JOptionPane.showMessageDialog(this, str);
            
            GDACNetAffxAnnotation an = new GDACNetAffxAnnotation();
            for (int j=0; j<n; j++)
            {
                an = m_List.GetAnnotation(j);
                anList.add(an.Description);
            }
        }
        catch (Throwable t)
        {
            javax.swing.JOptionPane.showMessageDialog(this, t.getMessage());
        }        
    }//GEN-LAST:event_okButtonActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        m_List.ReleaseCOMObject();
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        System.loadLibrary("GDACNetAffx");
        new TestNetAffx().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private java.awt.List anList;
    private javax.swing.JTextField pwdTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField connectionTextField;
    private javax.swing.JTextField userTextField;
    // End of variables declaration//GEN-END:variables
    
}
